### ISSUE TITLE
Send Item after reminder  fails

### ISSUE THREAD

**Issue by WeKeren** [kugelblitz-one/Fredo-Public#369]
Keren: Enter Email
Keren: /Reminder
Keren: /reminder 1m buy milk
 +1 (878) 206-6532: I will remind you in 1 minutes: buy milk
 **Keren: 👍😉😉👍👍**  
/reminder followed by date followed by time followed by the reminder text.
<img width="817" alt="Screen Shot 2022-12-15 at 12 12 37 AM" src="https://user-images.githubusercontent.com/113281951/207835229-fd9a358c-320c-429c-bd6b-05965c05e336.png">

**Comment by assafza** [comment]
Looks like you were already inside a reminder only flow. so you could not do anything other than that. we will solve this with the right message.
