### ISSUE TITLE
Text to image using OpenAI API

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#410]
API: https://beta.openai.com/docs/api-reference/images/create

When user is doing /image {{text}} we will send this {{text}} as the prompt to the image creation API and present to the user the result.

- [x] Flow: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764543429419375&cot=14
- [x] Mixpanel events(same as we did in /gpt): 
   - [x] NEW IMAGE PROMPT
   - [x] IMAGE SUCCESS RESPONSE
   - [ ] IMAGE FAILED RESPONSE
   - [x] Link to mixpanel doc: https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0
- [x] Help menu items in all menus (same as we did in /gpt): 🏞️ 13. /image  - Create an original image given a text prompt 
- [x] Testing testing testing :)

**Comment by lotem-vanunu** [comment]
1. What dimensions should the image be?
2. Should the answer to the user be the image or a link to the image?

**Comment by assafza** [comment]
@lotem-vanunu preferably it should be the image as a file + the link to the image.
About dimensions, what are the options? can't we show the original size?

**Comment by assafza** [comment]
@lotem-vanunu I have tested this feature and have some feedback:

- [ ] After 1 day the link sent is not opening again returns 404. probably some session expire. I do not see the value in having the image as a link. lets remove this option and just send the user an image.
- [ ] Resolution is indeed not as good. how can we determine the resolution? to have better resolution?

**Comment by assafza** [comment]
Add aliases 'img' , 'imagine'
