### ISSUE TITLE
Add multiple emails 

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#416]
We want to allow the option to users to connect multiple emails.
We need to make sure we are handlong the following:

- [x] Default flow:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764542139577023&cot=14

- [x] #hashtag flow:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764542139577076&cot=14

- [x] /listmaps flow:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764542139577051&cot=14

- [x] Help menu update:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764530842235488&cot=14

- [ ] Mixpanel events for Hashtag, default etc

**Comment by assafza** [comment]
@JerryVDP bug:
help menu is not functioning at a certain point of onboarding new email.
Steps to reproduce:
1. connect new email address
2. submit code
3. run /help
4. It is not showing correct "email" menu + I cant select options from the menu.


![Image](https://user-images.githubusercontent.com/25544824/214843448-ef32da49-b8e1-4bd2-b2f8-36dadfcf8fa1.png)

**Comment by JerryVDP** [comment]
@assafza 
Unable to reproduce:


![Image](https://user-images.githubusercontent.com/99589825/215455323-40f55671-0c1f-4d7d-891c-64c653f63016.png)


It could be that it's already fixed or something.

**Comment by assafza** [comment]
@JerryVDP Maping a new #hashtag email it is not verifying the email code again. 
Should send again for code validation for the new hashtagged address.

**Comment by JerryVDP** [comment]
@assafza 
I don't see a verification request design in Miro.
I'll wait for the design and then I'll develop it.

**Comment by assafza** [comment]
@JerryVDP here is a flow for the email hashtag verification code - see it in the light green boxes ( it is a copy of an existing flow we have in email)
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764542139577076&cot=14
