### ISSUE TITLE
Summarize articles links using OpenAI + google text-to-speech 

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#419]
Here is a function structure I generated from Open AI GPT.
https://www.notion.so/fredo-ai/Summarize-Articles-a6c55b10843a4176b2d30c08e59a57c7

Tasks:

- [ ] FLow for tldr command: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764545335523570&cot=14
- [ ] Add tldr to all menus: 📰 TLDR - Summarize articles (by URL)
- [ ] Mixpanel events:
  - [ ]  NEW TLDR REQUEST
  - [ ] TLDR SUCCESS
  - [ ] TLDR FAILED (added a property called "failed_reason" to include why was it failed which steps failed in the way)
  - [ ]  Link to mixpanel doc: https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0

**Comment by lotem-vanunu** [comment]
i started to check this mannually.
The HTML parsing isn't perfect; for example, it includes the header and footer of the page.
Although open AI succeeded in summarizing the article,

**Comment by assafza** [comment]
- [ ] We are on it and will check why this happened -> error message and check

**Comment by assafza** [comment]
@lotem-vanunu 
- [ ]  Add tldr to all menus: 📰 TLDR - Summarize articles (by URL)
