### ISSUE TITLE
Add additional character('@') to activate hashtags (#)

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#434]
We want '@' sign to be used as '#' in addition to '#'.

SO for example if I write @list2 it will activate the hashtag flow.
Also if I have #list1 I can address it with items with @list1.

Can you estimate time for making this happen pleae?

**Comment by JerryVDP** [comment]
Development: 3-5 hours
Testing: ~2 hours

**Comment by assafza** [comment]
@JerryVDP few use cases to handle:

After successfull mapping please also add the tip text explaining the user he can use the @ as well.
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764546152057056&cot=14

Should be applied to all successfull mappings.
