### ISSUE TITLE
New straight forward onboarding

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#436]
We want the onboarding process to be more straight forward and showing all the skills Fredo has.

- [ ] Please implement the welcome flow: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764545559535868&cot=14
    - [ ] 1. Welcome message has changed
    - [ ] 2. All blue boxes are new
    - [ ] 3. Add mixpanel events -> need to chnge "WELCOME SKILL" event properties based on user selection
          Link to event doc: https://docs.google.com/spreadsheets/d/1YCHJvsOiU--ei020Ag5BKigkVQpEUuqpNS6-NLa7zrU/edit#gid=0

**Comment by lotem-vanunu** [comment]
This is the exact text:
⏰⏰⏰\nNeed a reminder? Tell Fredo *when* and *what* and when the time comes, Fredo will send you a message.
\n_💡 Tip: start with the word *remind* or *reminder* and specify after that when and what._

*Examples:*
_remind me to pick up Jerry today @4pm_
_reminder 07-Sep-2023 08:00 breakfast at Tiffany_ \n
_Send *HELP* to return to main menu._


I added an underline to allow for italic text
