### ISSUE TITLE
API to set reminders from Email is not working

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#444]
https://stage.workflowy.clap.co.il/email-reminder

When trying to create reminder from this API it is not working - I am asuuming it is something to do with the fixes reminders?

**Comment by JerryVDP** [comment]
Can't reproduce.


![Image](https://user-images.githubusercontent.com/99589825/218305553-da3e4cb8-155e-4f6e-a7ad-5299d60c86d0.png)



![Image](https://user-images.githubusercontent.com/99589825/218305569-c17b5d9b-cede-4ed9-a912-0d7bf440f186.png)
