### ISSUE TITLE
gpt_reset command

### ISSUE THREAD

**Issue by assafza** [kugelblitz-one/Fredo-Public#476]
- [ ] Please add command "gpt_reset" to delete gpt history. 
- [ ] Add this text to the menu item desc: https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764545559535875&cot=14

**Comment by lotem-vanunu** [comment]
Is the command text "gpt_reset" or "gpt-reset"?
Does the bot return meesage after the deletion?

**Comment by assafza** [comment]
Hi @lotem-vanunu yes here it is:
https://miro.com/app/board/o9J_lttkfEA=/?moveToWidget=3458764547711382199&cot=14
